NumPy Arrays

In [1]:
my_list = [1, 2, 3]

In [2]:
import numpy as np

In [5]:
arr =  np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_list

[1, 2, 3]

In [9]:
my_mat = [[1,2,3],[4,5,6],[6,7,8]]

In [11]:
my_mat

[[1, 2, 3], [4, 5, 6], [6, 7, 8]]

In [12]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [17]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [19]:
np.zeros(3)

array([0., 0., 0.])

In [20]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

np.linspace : If we want evenly space 100 point from 0 to 5 

In [24]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

identity matrix using NumPy 

In [30]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Generate array of Random numbers

In [27]:
np.random.rand(5)

array([0.43971575, 0.10068504, 0.36662842, 0.95804212, 0.33379419])

In [28]:
np.random.rand(5,5)

array([[0.47175974, 0.90092589, 0.62116975, 0.02066108, 0.68063423],
       [0.93639943, 0.18819928, 0.02363443, 0.19214884, 0.35218757],
       [0.60962573, 0.26576609, 0.29774273, 0.99941761, 0.49187235],
       [0.20576492, 0.37462677, 0.77374771, 0.38876064, 0.69252898],
       [0.23483532, 0.38304013, 0.42450688, 0.00565102, 0.11977861]])

In [29]:
np.random.rand(5,10)

array([[0.6346326 , 0.51712815, 0.73543755, 0.98491629, 0.81538929,
        0.52998848, 0.44645138, 0.47409608, 0.86359055, 0.51352891],
       [0.51955554, 0.60372915, 0.00807923, 0.45298887, 0.07548139,
        0.81501299, 0.82215927, 0.86202314, 0.09426362, 0.10311372],
       [0.4962951 , 0.05717288, 0.89875648, 0.18275535, 0.02271339,
        0.36088177, 0.5398599 , 0.4915518 , 0.05572814, 0.86379807],
       [0.47907542, 0.451896  , 0.16681658, 0.99941348, 0.40024289,
        0.95518263, 0.51380249, 0.82486331, 0.03730364, 0.56750193],
       [0.31543416, 0.5018479 , 0.82458108, 0.61143523, 0.83013339,
        0.67804722, 0.43792474, 0.99271933, 0.01900021, 0.16379068]])

In [31]:
np.random.randn(5,4)

array([[-1.9619633 , -1.8261886 ,  0.54267946, -1.25026059],
       [ 0.04929484, -0.11636885,  0.63542341, -2.45002904],
       [-2.25194054,  0.82334206,  0.75751463,  0.66498897],
       [ 0.30279   ,  1.87768768,  0.71298929, -1.23682622],
       [-0.06479503,  0.05310791, -0.03291074,  0.07421057]])

In [32]:
np.random.randint(100,1000)

355

In [33]:
np.random.randint(100,1000, 10)

array([156, 283, 285, 441, 245, 300, 643, 899, 961, 770])

In [35]:
arr = np.arange(25)

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
ranarr = np.random.randint(0,50,10)

In [39]:
ranarr

array([ 1, 35, 34, 29, 25, 47,  7, 40, 30, 16])

In [41]:
ranarr.min()

1

In [42]:
ranarr.max()

47

In [43]:
ranarr.argmax()

5

In [44]:
ranarr

array([ 1, 35, 34, 29, 25, 47,  7, 40, 30, 16])